CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    tags VARCHAR(15)[] NOT NULL,
    summary VARCHAR(250) NOT NULL,
    media VARCHAR(100)[] NOT NULL,
    slug VARCHAR(115) NOT NULL,
    category VARCHAR(25) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    author INTEGER REFERENCES users(id),
    UNIQUE(title),
    UNIQUE(content)
);